#ansible
ansible_user: root

#Kubernetes -- this file is a mess
KUBE_CONF_DIR: /opt/kubeconfig
KUBE_USER_GROUP: kubeusers

KUBE_ADMIN_CONF: /etc/kubernetes/admin.conf
KUBE_CONF: "{{ KUBE_CONF_DIR }}/config"

#kubernetes
kubemaster_ip : 10.30.16.10
kubemaster_join_ip: 10.30.16.10:6443
#kube_auth_token : d1kaph.tju1wm1g5k67pdlf
kube_auth_token : x4hi8e.hjr8w5p902mmhrto 
kube_cert_hash : sha256:321e0bfef8f85e2a78803e9d238d6430d849b4070b4d3c0c4f3bdd175e8b1c55

pod_network_cidr: 10.244.0.0/16
advertise_address: 10.30.16.10

enable_dashboard: yes

user: user
user_g: user
