---
# Source: kube-prometheus/charts/exporter-kube-controller-manager/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "prometheus"
    chart: exporter-kube-controller-manager-0.1.7
    heritage: Helm
    prometheus: RELEASE-NAME
    release: RELEASE-NAME
    role: alert-rules
  name: RELEASE-NAME-exporter-kube-controller-manager
data:
  kube-controller-manager.rules: |-    
    groups:
    - name: kube-controller-manager.rules
      rules:
      - alert: K8SControllerManagerDown
        expr: absent(up{job="kube-controller-manager"} == 1)
        for: 5m
        labels:
          severity: critical
        annotations:
          description: There is no running K8S controller manager. Deployments and replication
            controllers are not making progress.
          runbook: https://coreos.com/tectonic/docs/latest/troubleshooting/controller-recovery.html#recovering-a-controller-manager
          summary: Controller manager is down
