- name: Create kube config
  file:
        path: "{{ KUBE_CONF_DIR }}"
        state: directory

- name: Copy admin.conf to /opt/kubeconfig directory
  copy:
          src: "{{ KUBE_ADMIN_CONF }}"
          dest: "{{ KUBE_CONF_DIR }}"
          owner: root
          group: kubeusers
          mode: 0775
          remote_src: true
