---
#Initialise flannel
- name: Copy flannel CNI plugin manifest
  copy:
          src: files/kube-flannel.yml
          dest: "{{ KUBE_CONF_DIR }}"
          owner: root
          group: "{{ KUBE_USER_GROUP }}"
          mode: 0775
- name: Initialise flannel kube service (coreDNS too)
  when: init_cluster is success 
  shell: |
          kubectl apply -f /opt/kubeconfig/kube-flannel.yml

