---
##Configure kubemaster

#Do kubeadm reset
- import_tasks: reset_cluster.yml

- name: Initialise  Kubernetes cluster
  when: cluster_reset
  shell: |
          kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
          --token {{ kube_auth_token }} \
          --apiserver-advertise-address {{ kubemaster_ip }}
  register: init_cluster

- name: Copy admin.conf to /opt/kubeconfig directory
  copy:
          src: "{{ KUBE_ADMIN_CONF }}"
          dest: "{{ KUBE_CONF_DIR }}"
          owner: root
          group: kubeusers
          mode: 0775
          remote_src: true

- import_tasks: init_flannel.yml
  environment:
          KUBECONFIG: /etc/kubernetes/admin.conf 
 
- import_tasks: dashboard.yml

