---
# Source: kube-prometheus/charts/prometheus/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.0.25
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-prometheus
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-prometheus
    namespace: default
