---
# Source: kube-prometheus/charts/prometheus/templates/prometheus.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.0.25
    heritage: Helm
    prometheus: RELEASE-NAME
    release: RELEASE-NAME
  name: RELEASE-NAME
spec:
  alerting:
    alertmanagers:
      - namespace: default
        name: RELEASE-NAME-alertmanager
        port: http
  baseImage: "quay.io/prometheus/prometheus"
  externalUrl: http://RELEASE-NAME-prometheus.default:9090
  paused: false
  replicas: 1
  logLevel:  info
  resources:
    {}
  retention: "24h"
  routePrefix: "/"
  serviceAccountName: RELEASE-NAME-prometheus

  serviceMonitorSelector:
    matchLabels:
      prometheus: RELEASE-NAME
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: RELEASE-NAME
  version: "v2.2.1"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: prometheus
              prometheus: RELEASE-NAME
