---
# Source: kube-prometheus/charts/prometheus/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.0.25
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus
