---
# Source: kube-prometheus/charts/prometheus/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.0.25
    heritage: Helm
    prometheus: RELEASE-NAME
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus
spec:
  sessionAffinity: "None"
  clusterIP: ""
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
    prometheus: RELEASE-NAME
  type: "ClusterIP"
