apiVersion: v1
kind: Pod
metadata:
  name: vulkan-container
spec:
  containers:
    - name: vulkan-container
      image: nvidia/vulkan:1.1.121
      #image: babbleshack/gpu-bench:latest
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["inf"]
      resources:
        limits:
          nvidia.com/gpu: 1
