apiVersion: v1
kind: Pod
metadata:
  name: gpu-bench-pod
spec:
  containers:
    - name: digits-container
      image: nvidia/cuda:11.0-runtime-ubuntu20.04
      #image: babbleshack/gpu-bench:latest
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["inf"]
      resources:
        limits:
          nvidia.com/gpu: 1
