---
# Source: kube-prometheus/charts/exporter-node/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    chart: "exporter-node-0.2.0"
    component: node-exporter
    heritage: "Helm"
    release: "RELEASE-NAME"
    prometheus: RELEASE-NAME
  name: RELEASE-NAME-exporter-node
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: exporter-node
      component: node-exporter
  namespaceSelector:
    matchNames:
      - "default"
  endpoints:
  - port: metrics
    interval: 15s
