nvidia_docker_repo_base_url: "https://nvidia.github.io/nvidia-docker"
nvidia_docker_repo_gpg_url: "{{ nvidia_docker_repo_base_url}}/gpgkey"
_ubuntu_repo_dist_name: "{{ ansible_distribution | lower }}{{ ansible_distribution_version }}"
_ubuntu_repo_file_name: "nvidia-docker.list"
_ubuntu_repo_file_path: "/etc/apt/sources.list.d/{{_ubuntu_repo_file_name}}"
nvidia_docker_wrapper_url: https://raw.githubusercontent.com/NVIDIA/nvidia-docker/master/nvidia-docker
nvidia_container_runtime_package_version: ''

docker_daemon_json:
  # set default runtime (required for kube and gpu docker container)
  runtimes: 
    nvidia:
      path: /usr/bin/nvidia-container-runtime
      runtimeArgs: []
  default-runtime: nvidia
