---
# Source: kube-prometheus/charts/exporter-kube-etcd/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    chart: "exporter-kube-etcd-0.1.9"
    component: kube-etcd
    heritage: "Helm"
    release: "RELEASE-NAME"
    prometheus: RELEASE-NAME
  name: RELEASE-NAME-exporter-kube-etcd
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: exporter-kube-etcd
      component: kube-etcd
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
