apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: {{ template "exporter-node.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: node-exporter
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "exporter-node.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "exporter-node.fullname" . }}
        component: node-exporter
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: node-exporter
          image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
          imagePullPolicy: "{{ .Values.nodeExporter.image.pullPolicy }}"
          args:
          - --web.listen-address=0.0.0.0:{{ .Values.nodeExporter.service.containerPort }}
          {{- if and .Values.nodeExporter.container .Values.nodeExporter.container.args }}
{{ toYaml .Values.nodeExporter.container.args | indent 10 }}
          {{- end }}
          {{- if and .Values.dcgmExporter.container .Values.nodeExporter.container.dcgmArg }}
{{ toYaml .Values.nodeExporter.container.dcgmArg | indent 10 }}
          {{- end -}}
          ports:
          - name: metrics
            containerPort: {{ .Values.nodeExporter.service.containerPort }}
            hostPort: {{ .Values.nodeExporter.service.containerPort }}
          resources:
{{ toYaml .Values.nodeExporter.resources | indent 12 }}
         {{- if and .Values.nodeExporter.container .Values.nodeExporter.container.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.nodeExporter.container.volumeMounts | indent 10 }}
          {{- if and .Values.dcgmExporter.container .Values.nodeExporter.container.dcgmMount }}
{{ toYaml .Values.nodeExporter.container.dcgmMount | indent 10 }}
          {{- end }}
         {{- end }}
        {{- with .Values.dcgmExporter }}
        - name: {{ .container.name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          securityContext:
{{ toYaml .container.securityContext | indent 12 }}
          volumeMounts:
{{ toYaml .container.volumeMounts | indent 10 }}
        {{- end }}
      volumes:
{{ toYaml .Values.nodeExporter.container.volumes | indent 6 }}
      {{- if and .Values.dcgmExporter.container .Values.dcgmExporter.container.volumes }}
{{ toYaml .Values.dcgmExporter.container.volumes | indent 6 }}
      {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
    {{- end }}
      hostNetwork: true
      hostPID: true
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
