---
# Source: kube-prometheus/charts/alertmanager/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: RELEASE-NAME
    app: alertmanager
    chart: alertmanager-0.0.13
    heritage: Helm
    release: RELEASE-NAME
  name: alertmanager-RELEASE-NAME
data:
  alertmanager.yaml: "Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KcmVjZWl2ZXJzOgotIG5hbWU6ICJudWxsIgpyb3V0ZToKICBncm91cF9ieToKICAtIGpvYgogIGdyb3VwX2ludGVydmFsOiA1bQogIGdyb3VwX3dhaXQ6IDMwcwogIHJlY2VpdmVyOiAibnVsbCIKICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJvdXRlczoKICAtIG1hdGNoOgogICAgICBhbGVydG5hbWU6IERlYWRNYW5zU3dpdGNoCiAgICByZWNlaXZlcjogIm51bGwi"
