---
# Source: kube-prometheus/charts/alertmanager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: RELEASE-NAME
    app: alertmanager
    chart: alertmanager-0.0.13
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-alertmanager
spec:
  clusterIP: ""
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    alertmanager: RELEASE-NAME
    app: alertmanager
  type: "ClusterIP"
