# Install kubernetes repository and components
- name: Add kubernetes repository key
  apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
- name: Add Kubernetes repository
  apt_repository: 
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    filename: 'kubernetes.list'
    update_cache: 'yes'
    state: present
- name: Install kubelet
  apt: 
    name: 'kubelet'
    state: 'present'
    update_cache: 'yes'
- name: Install kubadm
  apt: 
    name: 'kubeadm'
    state: 'present'
    update_cache: 'yes'
- name: Install kubctl
  apt: 
    name: 'kubectl'
    state: 'present'
    update_cache: 'yes'
- name: Install kub-cni
  apt:
    name: 'kubernetes-cni'
    state: 'present'
    update_cache: 'yes'

- name: Create kube config
  tags:
          - configure-kube
  file:
        path: "{{ KUBE_CONF_DIR }}" 
        state: directory

- name: Create kubelet config file
  tags:
          - configure-kube
  copy:
          src: files/kubelet-config.yml
          dest: "{{ KUBE_CONF_DIR }}/kubelet-config.yml"
          owner: root
          mode: 0755

- name: Copy kubelet service file
  tags:
          - configure-kube
  copy:
          src: files/kubelet.service
          dest: "/lib/systemd/system/kubelet.service"
          owner: root
          group: root
          force: yes
