---
# Source: kube-prometheus/charts/exporter-kube-state/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: exporter-kube-state
    chart: exporter-kube-state-0.1.15
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-exporter-kube-state
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-exporter-kube-state
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-exporter-kube-state
    namespace: default
