---
# Source: kube-prometheus/charts/exporter-kube-state/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: RELEASE-NAME-exporter-kube-state
  labels:
    app: exporter-kube-state
    component: kube-state
    heritage: Helm
    release: RELEASE-NAME
    chart: exporter-kube-state-0.1.15
    version: "v1.2.0"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: RELEASE-NAME-exporter-kube-state
  template:
    metadata:
      labels:
        app: RELEASE-NAME-exporter-kube-state
        component: kube-state
        release: RELEASE-NAME
        version: "v1.2.0"
    spec:
      containers:
      - name: exporter-kube-state
        image: "gcr.io/google_containers/kube-state-metrics:v1.2.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: exporter-kube-state-addon-resizer
        image: "gcr.io/google_containers/addon-resizer:1.7"
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --container=exporter-kube-state
          - --cpu=100m
          - --extra-cpu=1m
          - --memory=130Mi
          - --extra-memory=2Mi
          - --threshold=5
          - --deployment=RELEASE-NAME-exporter-kube-state
        resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 30Mi
      serviceAccountName: RELEASE-NAME-exporter-kube-state
