---
# Source: kube-prometheus/charts/exporter-kube-state/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: exporter-kube-state
    chart: exporter-kube-state-0.1.15
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-exporter-kube-state
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: ["extensions"]
  resources: ["deployments"]
  resourceNames: [RELEASE-NAME-exporter-kube-state]
  verbs: ["get", "update"]
