---
## Install Docker CE see docker documentation
- name: Install docker-ce cert
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository 
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'xenial'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable 
    state: present

- name: Add docker repository 
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'bionic'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable 
    state: present

#- name: Install docker-ce 18.06.2~ce~3-0~ubuntu
#  apt:
#    name: docker-ce=18.06.2~ce~3-0~ubuntu

- name: Install containerd
  apt:
    name: containerd.io=1.2.13-2

- name: Install docker-ce cli 5:19.03.12~3-0~ubuntu-bionic
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'bionic'
  apt:
    name: docker-ce-cli=5:19.03.12~3-0~ubuntu-bionic

- name: Install docker-ce 5:19.03.12~3-0~ubuntu-xenial
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'xenial'
  apt:
    name: docker-ce-cli=5:19.03.12~3-0~ubuntu-xenial

- name: copy docker daemon
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json

- name: make docker systemd service file
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Restart Docker Service  
    systemd:
      name: docker
      state: restarted
      daemon_reload: yes
