# Install docker
- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository 
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'xenial'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable 
    state: present

- name: Add docker repository 
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'bionic'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable 
    state: present

- name: Add docker repository (Disco)
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'disco'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Add docker repository (Focal)
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'focal'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install containerd
  apt:
    name: containerd.io=1.2.13-2

- name: Install docker-ce cli 5:19.03.12~3-0~ubuntu-bionic
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'bionic'
  apt:
    name: docker-ce-cli=5:19.03.12~3-0~ubuntu-bionic

- name: Install docker-ce 5:19.03.12~3-0~ubuntu-xenial
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'xenial'
  apt:
    name: docker-ce-cli=5:19.03.12~3-0~ubuntu-xenial

- name: Install docker-ce 5:19.03.12~3-0~ubuntu-focal
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'focal'
  apt:
    name: docker-ce-cli=5:19.03.12~3-0~ubuntu-focal

- name: Create Docker Daemon Config
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json

- name: Create docker systemd service dir
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower != 'focal'
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Restart Docker Service  
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes

#- name: install docker-ce-cli
#  apt:
#    name: docker-ce-cli
#
#- name: Install containerd.io
#  apt:
#    name: containerd.io
