---
## Install Docker CE see docker documentation
- name: Install docker-ce cert
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add docker-ce repository
  apt_repository: 
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
          filename: docker-ce.list
          state: present
          update_cache: yes
- name: Install docker-ce 17.9
  apt:
          name:  docker-ce=17.09.0~ce-0~ubuntu
