---
# Install core packages (docker, python, docker, kube-components)
- import_tasks: remove-swap.yml
      
- name: Install core packages
  vars:
    corepackages:
            - apt-transport-https
            - python
            - vim
  apt:
    name: "{{ corepackages }}"
    state: present

- import_tasks: docker.yml
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'bionic'


- import_tasks: dockerce.yml
  when:
          - ansible_distribution|lower == 'ubuntu'
          - ansible_distribution_release|lower == 'xenial'

- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Remove docker0 bridge
  shell: ip link delete docker0

- import_tasks: kubernetes.yml
