---
# Install core packages (docker, python, docker, kube-components)
- import_tasks: remove-swap.yml
      
- name: Install core packages
  vars:
    corepackages:
            - apt-transport-https
            - curl
            - software-properties-common
            - python
            - vim
  apt:
    name: "{{ corepackages }}"
    state: present

- import_tasks: docker.yml

- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: yes
