---
# Install core packages (docker, python, docker, kube-components)
hosts: all
- name: Install core packages
  vars:
    corepackages:
            - apt-transport-https
            - python
            - vim
  apt:
    name: "{{ corepackages }}"
    state: present

- name: Install docker CE 
  import_task: "docker-ce.yml"
  when: ansible_facts['ansible_distribution']|lower == 'ubuntu' and ansible_facts['distribution_release']|lower == 'xenial'

- name: Install docker.io 
  import_task: docker.yml
  when: ansible_facts['ansible_distribution']|lower == 'ubuntu' and ansible_facts['distribution_release']|lower == 'xenial'

- name: Start docker
  service:
    name: docker
    state: started

- name: Install Kubernetes components
  import_task: Kubernetes.yml
