---
# Install core packages (docker, python, docker, kube-components)
- name: Install core packages
  vars:
    corepackages:
            - apt-transport-https
            - python
            - vim
  apt:
    name: "{{ corepackages }}"
    state: present

- import_tasks: dockerce.yml
  when:
          - ansible_distribution|lower == 'ubuntu'
          - distribution_release|lower == 'bionic'


- import_tasks: docker.yml
  when:
          - ansible_distribution|lower == 'ubuntu'
          - distribution_release|lower == 'xenial'

- name: Start docker
  service:
    name: docker
    state: started

- import_tasks: kubernetes.yml
