---
# Source: kube-prometheus/charts/exporter-kube-scheduler/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    chart: "exporter-kube-scheduler-0.1.6"
    component: kube-scheduler
    heritage: "Helm"
    release: "RELEASE-NAME"
    prometheus: RELEASE-NAME
  name: RELEASE-NAME-exporter-kube-scheduler
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: exporter-kube-scheduler
      component: kube-scheduler
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
