---
# Source: kube-prometheus/charts/exporter-kube-scheduler/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exporter-kube-scheduler
    component: kube-scheduler
    heritage: Helm
    release: RELEASE-NAME
    chart: exporter-kube-scheduler-0.1.6
  name: RELEASE-NAME-exporter-kube-scheduler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10251
      protocol: TCP
      targetPort: 10251
  selector:
    k8s-app: kube-scheduler
  type: ClusterIP
