---
# Source: kube-prometheus/charts/grafana/templates/grafana-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: RELEASE-NAME-grafana
    chart: "grafana-0.0.24"
    heritage: "Helm"
    release: "RELEASE-NAME"
  name: RELEASE-NAME-grafana
spec:
  replicas: 1
  template:
    metadata:
      annotations:
      labels:
        app: RELEASE-NAME-grafana
        release: "RELEASE-NAME"
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:5.0.0
        env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME-grafana
              key: user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME-grafana
              key: password
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        ports:
        - name: web
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
      - name: grafana-watcher
        image: quay.io/coreos/grafana-watcher:v0.0.8
        args:
          - '--watch-dir=/var/grafana-dashboards'
          - '--grafana-url=http://127.0.0.1:3000'
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME-grafana
              key: user
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME-grafana
              key: password
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
          - name: grafana-dashboards
            mountPath: /var/grafana-dashboards
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-dashboards
          configMap:
            name: RELEASE-NAME-grafana
