---
# Source: kube-prometheus/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: RELEASE-NAME-grafana
    chart: "grafana-0.0.24"
    heritage: "Helm"
    release: "RELEASE-NAME"
  name: RELEASE-NAME-grafana
type: Opaque
data:
  password: "YWRtaW4="
  user: "YWRtaW4="
