---
- name: check distro
  fail:
    msg: "distro {{ansible_facts['distribution'] }} not supported"
  when: ansible_facts['distribution'] != 'Ubuntu' and ansible_os_family != 'RedHat'

- name: pre-requsite tasks
  include_tasks: pre-install.yml
  when: ansible_distribution == 'Ubuntu'

- name: set docker daemon default configuration to nvidia
  copy:
    content: " {{ docker_daemon_json | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: reload docker


# avoiding docker version pinning
- name: grab nvidia-docker wrapper 
  get_url:
    url: "{{ nvidia_docker_wrapper_url }}"
    dest: /usr/local/bin/nvidia-docker
    mode: 0755
    owner: root
    group: root
