---
- name: remove nvidia docker packages
  apt: 
    name: 
      - nvidia-docker
      - nvidia-docker2
    state: absent
    autoremove: yes
    purge: yes

- name: add nvidia gpg key
  apt_key:
    url: "{{ nvidia_docker_repo_gpg_url }}"
    state: present

- name: add nvidia docker repo
  get_url:
    # 18.04 because there is no support for 19.04 just yet..... 
    url: "{{ nvidia_docker_repo_base_url }}/ubuntu18.04/{{ _ubuntu_repo_file_name }}"
    dest: "{{ _ubuntu_repo_file_path }}"
    mode: 0644
    owner: root
    group: root

- name: install packages
  apt:
    name: nvidia-container-runtime
    state: present
    update_cache: yes
  notify: reload docker
